language: rust
os:
  - osx
  - windows
branches:
  only:
    - master
rust:
  - nightly
addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
      - "./target"
      - "./resources"
script:
  cargo build -Z features=itarget --release
