language: rust
os:
  - osx
  - windows
branches:
  only:
    - master
rust:
  - nightly
script:
  - cargo build -Z features=itarget --release
after_script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install zip ; fi
  - zip -r artifacts/${PROJECT_NAME}-${TRAVIS_OS_NAME}-${TRAVIS_BUILD_NUMBER}.zip target resources
addons:
  artifacts:
    s3_region: "us-west-2"
    paths:
      - ./artifacts
    target_paths:
      - /$TRAVIS_BUILD_NUMBER
