[package]
name = "evil_penguin"
version = "0.6.0"
authors = ["Paul Reesman <paul.r.reesman@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = { version = "^0.13.2", features = ["vulkan", "nightly"] }
const-concat = { git = "https://github.com/reesmanp/const-concat" }
serde = { version = "1.0", features = ["derive"] }
